### ISSUE TITLE
No FBI outputs in the metrics folder

### ISSUE THREAD

**Issue by pinghongyeh** [muscbridge/PyDesigner#301]
Hi PyDesigner Team, 

Thank you for the package. 
I have ran several our data, but so far I was not able to find the FBI results. 
Here is the list of files in the metrics folder. 
DT.nii			dki_kfa.nii		dki_rk.nii		dti_fa.nii		dti_rd.nii		wmti_eas_rd.nii
KT.nii			dki_mk.nii		dki_trace.nii		dti_fe.nii		dti_trace.nii		wmti_eas_tort.nii
dki_ak.nii		dki_mkt.nii		dti_ad.nii		dti_md.nii		wmti_awf.nii		wmti_ias_da.nii
dki_dsistudio.fib	dki_odf.nii		dti_dsistudio.fib	dti_odf.nii		wmti_eas_ad.nii

The command syntax I used, 

python $pydesignerfile --mask --smooth --csf_fsl --adv --resume --force $dwipath/pydesigner_invx_invy_rician_3shells_2023/DWI_3shells_plusb0.nii.gz -o $dwipath/pydesigner_invx_invy_rician_3shells_2023

the $pydesignerfile is the pydesigner.py/

I wonder  whether it had terminated due to insufficient memory. I had tested it on MAC OS with 64GB or 94 GB.

Best, 
Ping

**Comment by TheJaeger** [comment]
Hi Ping,

Which b-values is your dataset composed of?

**Comment by pinghongyeh** [comment]
Hi Siddhartha,

It is composed of b=1000,2000,3000 (90 directions for each shell) plus 18
b0.

Thanks.
Ping

**Comment by TheJaeger** [comment]
That would be a DKI dataset. FBI requires a minimum of b=4000, up to a max of b=12,000.

**Comment by pinghongyeh** [comment]
Thank you for your clarification. My bad, I thought b=3000 would be
sufficient.

Best,
Ping

**Comment by TheJaeger** [comment]
Closing issue because it is not a cause by PyDesigner. Dataset in question is not compatible with FBI.
