### ISSUE TITLE
Question about input

### ISSUE THREAD

**Issue by ken-sakaie** [muscbridge/PyDesigner#309]
Hi,

I'm getting an error when I run PyDesigner. It looks to me as if having more than one input file causes issues.

Traceback (most recent call last):
  File "/usr/local/bin/pydesigner", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/designer/pydesigner.py", line 262, in main
    image = DWIParser(args.dwi)
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/util.py", line 364, in __init__
    ftype.append(mrinfoutil.format(self.DWIlist[i]).lower())
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/mrinfoutil.py", line 61, in format
    type = getconsole(path, '-format')
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/mrinfoutil.py", line 32, in getconsole
    raise OSError('Input path does not exist. Please ensure that the '
OSError: Input path does not exist. Please ensure that the folder or file specified exists.

Here's what I did:

First, this command ran fine:
docker run --user "$(id -u):$(id -g)" -it --rm -v /path/to/my/data:/data dmri/neurodock pydesigner --standard --output /data/processed /data/nifti/data.nii.gz

However, if I add another file, I get the above error:
docker run --user "$(id -u):$(id -g)" -it --rm -v /path/to/my/data:/data dmri/neurodock pydesigner --standard --output /data/processed /data/nifti/data.nii.gz,/data/nifti/reverse_phase_encode.nii.gz

As a sanity check, I made copies of data.nii.gz, data.bval, data.bvec and data.json and called them tmp.nii.gz, tmp.bval, tmp.bvec and tmp.json then ran:
docker run --user "$(id -u):$(id -g)" -it --rm -v /path/to/my/data:/data dmri/neurodock pydesigner --standard --output /data/processed /data/nifti/data.nii.gz,/data/nifti/tmp.nii.gz

I get the same error.

Note: I had to add the --user "$(id -u):$(id -g)" to deal with permissions issues with docker.
Also, I created "fake" reverse_phase_encode.bval and reverse_phase_encode.bvec files that weren't generated by dcm2niix. reverse_phase_encode.nii.gz is a single reverse phase encode b=0 scan.

Tangential question: when will the RPG Gibbs ringing correction be available?

Thanks!
Ken

**Comment by gonzoBlackMamba** [comment]
Hi  @ken-sakaie,

Try it without the comma between the two DWI files. I think that it is no longer necessary in the updated pyDesigner versions (at least that is the case in the non-docker version).

-Hunter

**Comment by gonzoBlackMamba** [comment]
Glad it is working now! We will update the wiki page to reflect this.

There is code out there that is compiled C++ that runs in MATLAB from the NYU group (https://github.com/NYU-DiffusionMRI/rpg-degibbs). I suspect that the MRTrix dev team is probably working on implementing it, and if they do, we will most likely update our pipeline to include it but there is nothing definitive at the current time on our end.

-HM
